---@meta

-- Auto-generated EmmyLua definitions for Runeforge 0.0.1 script modules
-- Do not edit this file manually

---@class actions
actions = {}

--- Add new action
---@param name string
---@param action Action<any>
function actions.addAction(name, action) end

--- Execute action
---@param name string
---@param parameter any
function actions.executeAction(name, parameter) end


---@class ai
ai = {}

--- Add brain
---@param name string
---@param action Closure
function ai.addBrain(name, action) end


---@class logger
logger = {}

--- Log message with debug level
---@param message string
---@param args any[]
function logger.debug(message, ...) end

--- Log message with error level
---@param message string
---@param args any[]
function logger.error(message, ...) end

--- Log message with info level
---@param message string
---@param args any[]
function logger.info(message, ...) end

--- Log message with warning level
---@param message string
---@param args any[]
function logger.warning(message, ...) end


---@class mapGen
mapGen = {}

--- add step to map generator
---@param name string
---@param genFunction DynValue
function mapGen.addStep(name, genFunction) end


---@class names
names = {}

--- Generate new name
---@param type string
---@return string
function names.generateName(type) end


---@class random
random = {}

--- Get random boolean value
---@return boolean
function random.bool() end

--- Get random integer between min and max
---@param min integer
---@param max integer
---@return integer
function random.int(min, max) end

--- Roll a dice expression
---@param dice string
---@return integer
function random.roll(dice) end


---@class tiles
tiles = {}

--- create tile from tag or tileId
---@param tileOrTag string
---@return ColoredGlyph
function tiles.create(tileOrTag) end


